services:
  playwright-url-validator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BASE_URL: ${BASE_URL:-https://a30.vehr.veradigmcloud.com/userportal/apps}
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
